apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openldap
  template:
    metadata:
      labels:
        app: openldap
    spec:
      containers:
      - name: openldap
        image: osixia/openldap:1.5.0
        env:
        - name: LDAP_ORGANISATION
          value: "MyCompany"
        - name: LDAP_DOMAIN
          value: "mycompany.com"
        - name: LDAP_ADMIN_PASSWORD
          value: "adminpassword"
        - name: LDAP_CONFIG_PASSWORD
          value: "configpassword"
        ports:
        - containerPort: 389
        - containerPort: 636
        volumeMounts:
        - name: ldap-data
          mountPath: /var/lib/ldap
        - name: ldap-config
          mountPath: /etc/ldap/slapd.d
      volumes:
      - name: ldap-data
        emptyDir: {}
      - name: ldap-config
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: openldap
spec:
  selector:
    app: openldap
  ports:
  - name: ldap
    port: 389
    targetPort: 389
  - name: ldaps
    port: 636
    targetPort: 636
